<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Hasil Simulasi Deposito</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #000;
            padding-bottom: 10px;
        }

        .header h2 {
            margin: 0;
            font-size: 18px;
            text-transform: uppercase;
        }

        .header p {
            margin: 4px 0 0;
            font-size: 11px;
        }

        .box {
            border: 1px solid #000;
            padding: 12px;
            margin-bottom: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th {
            text-align: left;
            width: 35%;
            background: #f2f2f2;
        }

        td, th {
            border: 1px solid #000;
            padding: 8px;
        }

        .highlight {
            font-weight: bold;
            color: #0a7d00;
        }

        .total {
            font-size: 14px;
            font-weight: bold;
            color: #0033cc;
        }

        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: right;
            color: #555;
        }
    </style>
</head>
<body>

    <!-- HEADER -->
    <div class="header">
        <h2>Laporan Simulasi Deposito</h2>
        <p>Generated by Sistem Simulasi Deposito Bank</p>
    </div>

    <!-- INFO UTAMA -->
    <div class="box">
        <table>
            <tr>
                <th>Nama Bank</th>
                <td>{{ $bank->nama_bank }}</td>
            </tr>
            <tr>
                <th>Suku Bunga</th>
                <td>{{ $bank->suku_bunga_dasar }}%</td>
            </tr>
            <tr>
                <th>Nominal Deposito</th>
                <td>Rp {{ number_format($nominal, 0, ',', '.') }}</td>
            </tr>
            <tr>
                <th>Jangka Waktu</th>
                <td>{{ $jangka_waktu }} bulan</td>
            </tr>
        </table>
    </div>

    <!-- HASIL -->
    <div class="box">
        <table>
            <tr>
                <th>Bunga Diterima</th>
                <td class="highlight">
                    Rp {{ number_format($bunga_diterima, 0, ',', '.') }}
                </td>
            </tr>
            <tr>
                <th>Total Akhir Deposito</th>
                <td class="total">
                    Rp {{ number_format($total_akhir, 0, ',', '.') }}
                </td>
            </tr>
        </table>
    </div>

    <!-- FOOTER -->
    <div class="footer">
        Dicetak pada: {{ date('d M Y, H:i') }}
    </div>

</body>
</html>
